language: "es"

reviews:
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/*.test.ts"
    - "!**/*.test.tsx"
    - "!**/node_modules/**"
  review_instructions: |
    - Seguir convenciones de CLAUDE.md
    - Usar conventional commits
    - Verificar tipos TypeScript
    - Revisar imports no usados
