import { describe, expect, it } from 'vitest';
import type { EntityDesign, FieldDesign } from '../types';
import type { ForeignKeyConfig, RelationDesign } from '../types/relation';
import { generateSQL } from './sqlGenerator';

describe('sqlGenerator', () => {
  // Helper to create a field with defaults
  const createField = (
    overrides: Partial<FieldDesign> & { id: string; name: string },
  ): FieldDesign => ({
    columnName: overrides.name,
    type: 'String',
    nullable: true,
    unique: false,
    validations: [],
    ...overrides,
  });

  // Helper to create a foreign key config
  const createForeignKey = (
    columnName: string,
    overrides: Partial<ForeignKeyConfig> = {},
  ): ForeignKeyConfig => ({
    columnName,
    nullable: false,
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
    ...overrides,
  });

  // Helper to create a relation with defaults
  const createRelation = (
    overrides: Partial<RelationDesign> & {
      id: string;
      sourceEntityId: string;
      targetEntityId: string;
      sourceFieldName: string;
    },
  ): RelationDesign => ({
    type: 'ManyToOne',
    bidirectional: false,
    fetchType: 'LAZY',
    cascade: [],
    foreignKey: createForeignKey(`${overrides.sourceFieldName}_id`),
    ...overrides,
  });

  // Helper to create an entity with defaults
  const createEntity = (overrides: Partial<EntityDesign> = {}): EntityDesign => ({
    id: 'entity-1',
    name: 'User',
    tableName: 'users',
    description: '',
    position: { x: 0, y: 0 },
    fields: [],
    config: {
      generateController: true,
      generateService: true,
      enableCaching: false,
    },
    ...overrides,
  });

  describe('generateSQL', () => {
    it('should generate SQL for a simple entity', () => {
      const entities: EntityDesign[] = [
        createEntity({
          name: 'Product',
          tableName: 'products',
          fields: [
            createField({ id: 'f1', name: 'name', nullable: false }),
            createField({ id: 'f2', name: 'price', columnName: 'price', type: 'BigDecimal' }),
          ],
        }),
      ];

      const sql = generateSQL(entities, [], 'Test Project');

      expect(sql).toContain('CREATE TABLE products');
      expect(sql).toContain('name VARCHAR(255) NOT NULL');
      expect(sql).toContain('price DECIMAL(19,2)');
      expect(sql).toContain('id BIGSERIAL PRIMARY KEY');
    });

    it('should include project header', () => {
      const entities: EntityDesign[] = [createEntity()];
      const sql = generateSQL(entities, [], 'My API Project');

      expect(sql).toContain('Generated by APiGen Studio');
      expect(sql).toContain('Project: My API Project');
    });

    it('should generate UNIQUE constraint', () => {
      const entities: EntityDesign[] = [
        createEntity({
          fields: [createField({ id: 'f1', name: 'email', nullable: false, unique: true })],
        }),
      ];

      const sql = generateSQL(entities, [], 'Test');

      expect(sql).toContain('email VARCHAR(255) NOT NULL UNIQUE');
    });

    it('should generate DEFAULT value', () => {
      const entities: EntityDesign[] = [
        createEntity({
          fields: [createField({ id: 'f1', name: 'status', defaultValue: "'active'" })],
        }),
      ];

      const sql = generateSQL(entities, [], 'Test');

      expect(sql).toContain("DEFAULT 'active'");
    });

    it('should generate base audit fields', () => {
      const entities: EntityDesign[] = [createEntity()];
      const sql = generateSQL(entities, [], 'Test');

      expect(sql).toContain('estado VARCHAR(20)');
      expect(sql).toContain('fecha_creacion TIMESTAMP');
      expect(sql).toContain('fecha_actualizacion TIMESTAMP');
      expect(sql).toContain('creado_por VARCHAR(100)');
      expect(sql).toContain('modificado_por VARCHAR(100)');
      expect(sql).toContain('version BIGINT');
    });

    it('should generate foreign key for ManyToOne relation', () => {
      const entities: EntityDesign[] = [
        createEntity({ id: 'order-1', name: 'Order', tableName: 'orders' }),
        createEntity({ id: 'customer-1', name: 'Customer', tableName: 'customers' }),
      ];

      const relations: RelationDesign[] = [
        createRelation({
          id: 'rel-1',
          sourceEntityId: 'order-1',
          sourceFieldName: 'customer',
          targetEntityId: 'customer-1',
        }),
      ];

      const sql = generateSQL(entities, relations, 'Test');

      expect(sql).toContain('customer_id BIGINT NOT NULL');
      expect(sql).toContain('FOREIGN KEY (customer_id)');
      expect(sql).toContain('REFERENCES customers(id)');
      expect(sql).toContain('ON DELETE CASCADE');
    });

    it('should generate join table for ManyToMany relation', () => {
      const entities: EntityDesign[] = [
        createEntity({ id: 'student-1', name: 'Student', tableName: 'students' }),
        createEntity({ id: 'course-1', name: 'Course', tableName: 'courses' }),
      ];

      const relations: RelationDesign[] = [
        createRelation({
          id: 'rel-1',
          type: 'ManyToMany',
          sourceEntityId: 'student-1',
          sourceFieldName: 'courses',
          targetEntityId: 'course-1',
          foreignKey: createForeignKey('student_id'),
          joinTable: {
            name: 'student_course',
            joinColumn: 'student_id',
            inverseJoinColumn: 'course_id',
          },
        }),
      ];

      const sql = generateSQL(entities, relations, 'Test');

      expect(sql).toContain('CREATE TABLE student_course');
      expect(sql).toContain('student_id BIGINT NOT NULL');
      expect(sql).toContain('course_id BIGINT NOT NULL');
      expect(sql).toContain('PRIMARY KEY (student_id, course_id)');
    });

    it('should generate index for foreign keys', () => {
      const entities: EntityDesign[] = [
        createEntity({ id: 'post-1', name: 'Post', tableName: 'posts' }),
        createEntity({ id: 'author-1', name: 'Author', tableName: 'authors' }),
      ];

      const relations: RelationDesign[] = [
        createRelation({
          id: 'rel-1',
          sourceEntityId: 'post-1',
          sourceFieldName: 'author',
          targetEntityId: 'author-1',
          foreignKey: createForeignKey('author_id', { nullable: true, onDelete: 'SET_NULL' }),
        }),
      ];

      const sql = generateSQL(entities, relations, 'Test');

      expect(sql).toContain('CREATE INDEX idx_posts_author_id ON posts(author_id)');
    });

    it('should map Java types to SQL types correctly', () => {
      const entities: EntityDesign[] = [
        createEntity({
          fields: [
            createField({ id: 'f1', name: 'text' }),
            createField({ id: 'f2', name: 'count', type: 'Integer' }),
            createField({ id: 'f3', name: 'total', type: 'Long' }),
            createField({ id: 'f4', name: 'price', type: 'BigDecimal' }),
            createField({ id: 'f5', name: 'active', type: 'Boolean' }),
            createField({
              id: 'f6',
              name: 'birthDate',
              columnName: 'birth_date',
              type: 'LocalDate',
            }),
            createField({
              id: 'f7',
              name: 'createdAt',
              columnName: 'created_at',
              type: 'LocalDateTime',
            }),
            createField({ id: 'f8', name: 'uuid', type: 'UUID' }),
          ],
        }),
      ];

      const sql = generateSQL(entities, [], 'Test');

      expect(sql).toContain('text VARCHAR(255)');
      expect(sql).toContain('count INTEGER');
      expect(sql).toContain('total BIGINT');
      expect(sql).toContain('price DECIMAL(19,2)');
      expect(sql).toContain('active BOOLEAN');
      expect(sql).toContain('birth_date DATE');
      expect(sql).toContain('created_at TIMESTAMP');
      expect(sql).toContain('uuid UUID');
    });

    it('should use default project name when not provided', () => {
      const entities: EntityDesign[] = [createEntity()];
      const sql = generateSQL(entities, []);

      expect(sql).toContain('Project: API Project');
    });

    it('should handle empty entities array', () => {
      const sql = generateSQL([], [], 'Empty Project');

      expect(sql).toContain('Generated by APiGen Studio');
      expect(sql).not.toContain('CREATE TABLE');
    });

    it('should order entities by dependencies', () => {
      const entities: EntityDesign[] = [
        createEntity({ id: 'child-1', name: 'Child', tableName: 'children' }),
        createEntity({ id: 'parent-1', name: 'Parent', tableName: 'parents' }),
      ];

      const relations: RelationDesign[] = [
        createRelation({
          id: 'rel-1',
          sourceEntityId: 'child-1',
          sourceFieldName: 'parent',
          targetEntityId: 'parent-1',
        }),
      ];

      const sql = generateSQL(entities, relations, 'Test');

      // Parent table should appear before child table (parent has no FK dependencies)
      const parentIndex = sql.indexOf('CREATE TABLE parents');
      const childIndex = sql.indexOf('CREATE TABLE children');

      expect(parentIndex).toBeLessThan(childIndex);
    });
  });
});
